git:
  submodules: true

sudo: false

language: node_js

node_js:
  - node

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew unlink python && brew install protobuf && brew install snappy && brew install lz4"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - npm run setup-bluzelle-js
  - mkdir -p daemon-binary
  - cd daemon-binary
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      ARTIFACTORY_REPO=https://bluzelle.jfrog.io/bluzelle/OSX/
      LATEST_BLUZELLE_SWARMDB_TARBALL=$(curl ${ARTIFACTORY_REPO} | grep bluzelle-swarmdb | tail -1 | grep -o '"[^"]*"' | tr -d '"')
    else
      ARTIFACTORY_REPO=https://bluzelle.jfrog.io/bluzelle/osx-dev/
      LATEST_BLUZELLE_SWARMDB_TARBALL=$(curl ${ARTIFACTORY_REPO} | grep unstable-bluzelle-swarmdb | tail -1 | grep -o '"[^"]*"' | tr -d '"')
    fi
  - curl -0 ${ARTIFACTORY_REPO}${LATEST_BLUZELLE_SWARMDB_TARBALL} | tar -zx --strip-components=1
  - echo ${LATEST_BLUZELLE_SWARMDB_TARBALL}
  - cd ../
  - npm link-daemon ../daemon-binary

script:
  - yarn test
