git:
  submodules: true

sudo: false

language: node_js

node_js:
  - node

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew unlink python && brew install protobuf && brew install snappy && brew install lz4"

before_install:
  - rm -rf daemon-build
  - mkdir -p daemon-build/output/
  - cd daemon-build/output
  - export LATEST_BLUZELLE_SWARMDB=$(curl https://bluzelle.jfrog.io/bluzelle/OSX/ | grep bluzelle-swarmdb | tail -1 | grep -o '"[^"]*"' | tr -d '"')
  - curl -0 https://bluzelle.jfrog.io/bluzelle/OSX/$LATEST_BLUZELLE_SWARMDB | tar -zx
  - cp ./$(echo $LATEST_BLUZELLE_SWARMDB | sed 's/\.tar\.gz//g')/swarm ./
  - cd ../../

script:
  - yarn test-daemon
