const {includes, filter} = require('lodash');
const {readFileSync, readdirSync} = require('fs');

const PATH_TO_DAEMON = './daemon-build/';

const logUtils = {
    fileExists: () => {
        // Log file is generated by Daemon in /output folder
        return filter(logUtils.readDir('output'), file => includes(file, '.log'))[0];
    },
    fileMoved: logFileName => {
        // Log file is moved to /output/logs after Daemon is stopped
        return filter(logUtils.readDir('output/logs'), files => includes(files, logFileName))[0];
    },
    readFile: (dirPath, fileName) => {
        return readFileSync(PATH_TO_DAEMON + dirPath + fileName, 'utf8');
    },
    readDir: path => {
        return readdirSync(PATH_TO_DAEMON + path);
    },
    checkFilesConsistency: (done, dataObj) => {
        let value;
        let results = [];

        for (let key in dataObj) {
            if (!value) {
                value = dataObj[key];
            }

            results.push(value === dataObj[key]);
        }

        if (results.every(v => v)) {
            done()
        }
    }
};

module.exports = logUtils;
